// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nolewmfixuojseylfywu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vbGV3bWZpeHVvanNleWxmeXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzI3MTQsImV4cCI6MjA2MzE0ODcxNH0.Njnikn__PawGPH7VrqK3ZRC9cI9_pXPzquZn7AOt62U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);