// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skuqmvayxpuxvboxqawh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdXFtdmF5eHB1eHZib3hxYXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjIwNzQsImV4cCI6MjA2Mjk5ODA3NH0.smOKG9Gw84kqh2_mbUosxJj5U5cNx9baOH244IfdFys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);